---
- name: "From S3 | Downloading content"
  shell: "aws s3 sync s3://{{ syncs3content.storage.bucket }} . --profile {{ syncs3content.storage.profile }}"
  args:
    chdir: "{{ syncs3content.storage.dir }}"

- name: "From S3 | Uncompress the DB"
  shell: "gzip -dfk {{ item.name }}.sql.gz"
  args:
    chdir: "{{ syncs3content.storage.dir }}/{{ syncs3content.storage.dbdir }}"    
  with_items: "{{ syncs3content.from.databases }}"

- name: "From S3 | DB replacements"
  replace:
    dest: "{{ syncs3content.storage.dir }}/{{ syncs3content.storage.dbdir }}/{{ syncs3content.from.databases.0.name }}.sql"
    regexp: "{{ item.regex }}"
    replace: "{{ item.replace }}" 
  with_items: "{{ syncs3content.from.databases.0.replacements }}"

- name: "From S3 | Import DB"
  become: yes
  mysql_db:
    name: "{{ item.name }}"
    state: import
    target: "{{ syncs3content.storage.dir }}/{{ syncs3content.storage.dbdir }}/{{ item.name }}.sql"  
  with_items: "{{ syncs3content.from.databases }}"

- name: "From S3 | Delete DB File"
  file:
    path: "{{ item.name }}.sql"
    state: absent
  args:
    chdir: "{{ syncs3content.storage.dir }}/{{ syncs3content.storage.dbdir }}"    
  async: 3600
  poll: 0
  with_items: "{{ syncs3content.from.databases }}"
  when: "{{ syncs3content.from.delete_file }}"

- name: "From S3 | Execute post commands, please wait ..."
  shell: "{{ item }}"
  with_items: "{{ syncs3content.from.post_commands }}"
  async: 3600
  poll: 0

- name: "From S3 | Send notification to Slack"
  slack:
    token: "{{ syncs3content.slack.token }}"
    msg: "{{ syncs3content.slack.message }}"
    attachments:
      - title: "Sync content from S3"
        text: "{{ syncs3content.from.description }}"
        color: good
        fields:
          - title: "DataBase"
            value: "{% for db in syncs3content.from.databases %}{{ db.name }} {% endfor %}"
            short: "true"
          - title: "S3 Bucket"
            value: "{{ syncs3content.storage.bucket }}"
            short: "true"
          - title: "Storage directory"
            value: "{{ syncs3content.storage.dir }}"
            short: "true"
          - title: "Action"
            value: "{{ syncs3content.action }}"
            short: "true"
    username: "{{ syncs3content.slack.username }}"
    channel: "{{ syncs3content.slack.channel }}"
    icon_emoji: "{{ syncs3content.slack.icon_emoji }}"
  when: syncs3content.slack.token is defined
