---
- name: Fix ownership of content directory
  become: yes
  file:
    path: "{{ syncs3content.from.storage.dir }}"
    state: directory
    owner: "{{ syncs3content.from.storage.user }}"
    recurse: yes

- name: "From S3 | Downloading content"
  shell: "aws s3 sync s3://{{ syncs3content.from.storage.bucket }} .{% if syncs3content.from.storage.profile %} --profile {{ syncs3content.from.storage.profile }}{% endif %}"
  args:
    chdir: "{{ syncs3content.from.storage.dir }}"

- name: "From S3 | Uncompress the DB"
  shell: "gzip -dfk {{ item.name }}.sql.gz"
  args:
    chdir: "{{ syncs3content.from.storage.dir }}/{{ syncs3content.from.storage.dbdir }}"
  with_items: "{{ syncs3content.from.databases }}"

- name: "From S3 | Include DB replacements"
  include: db_replacements.yml
  with_items: "{{ syncs3content.from.databases }}"
  loop_control:
    loop_var: db_item

- name: "From S3 | Import DB"
  become: yes
  mysql_db:
    name: "{{ item.name }}{{ syncs3content.from.db_suffix }}"
    state: import
    target: "{{ syncs3content.from.storage.dir }}/{{ syncs3content.from.storage.dbdir }}/{{ item.name }}.sql"
  with_items: "{{ syncs3content.from.databases }}"

- name: "From S3 | Delete DB File"
  file:
    path: "{{ item.name }}.sql"
    state: absent
  args:
    chdir: "{{ syncs3content.from.storage.dir }}/{{ syncs3content.from.storage.dbdir }}"
  async: 3600
  poll: 0
  with_items: "{{ syncs3content.from.databases }}"
  when: "{{ syncs3content.from.delete_file }}"

- name: "From S3 | Execute post commands, please wait ..."
  shell: "{{ item }}"
  with_items: "{{ syncs3content.from.post_commands }}"
  async: 3600
  poll: 0

- name: "From S3 | Send notification to Slack"
  slack:
    token: "{{ syncs3content.slack.token }}"
    msg: "{{ syncs3content.slack.message }}"
    attachments:
      - title: "Sync content from S3"
        text: "{{ syncs3content.from.description }}"
        color: good
        fields:
          - title: "DataBase"
            value: "{% for db in syncs3content.from.databases %}{{ db.name }} {% endfor %}"
            short: "true"
          - title: "S3 Bucket"
            value: "{{ syncs3content.from.storage.bucket }}"
            short: "true"
          - title: "Storage directory"
            value: "{{ syncs3content.from.storage.dir }}"
            short: "true"
          - title: "Action"
            value: "{{ syncs3content.action }}"
            short: "true"
    username: "{{ syncs3content.slack.username }}"
    channel: "{{ syncs3content.slack.channel }}"
    icon_emoji: "{{ syncs3content.slack.icon_emoji }}"
  async: 3600
  poll: 0    
  when:
    - syncs3content.slack.token is defined
    - syncs3content.slack.channel
