---
- block:
    - name: Sync content to S3
      include: tos3.yml
  when: syncs3content.action == "tos3"
  tags: tos3

- block:
    - name: Sync content from S3
      include: froms3.yml
  when: syncs3content.action == "froms3"
  tags: froms3
