---
- name: "To S3: Export the DB"
  become: yes
  mysql_db:
    name: "{{ syncs3content.to.database.name }}"
    state: dump
    target: "{{ syncs3content.to.storage.dir }}/{{ syncs3content.to.database.dir }}/{{ syncs3content.to.database.name }}.sql"
    login_host: "{{ syncs3content.to.database.host | default('localhost') }}"
    login_password: "{{ syncs3content.to.database.password | default('') }}"
    login_user: "{{ syncs3content.to.database.user | default('') }}"

- name: "To S3: Compress the DB"
  shell: "tar -pczf {{ syncs3content.to.database.dir }}/{{ syncs3content.to.database.name }}.sql.tar.gz -C {{ syncs3content.to.database.dir }} {{ syncs3content.to.database.name }}.sql"
  args:
    chdir: "{{ syncs3content.to.storage.dir }}"

- name: "To S3: Delete DB File"
  file:
    path: "{{ syncs3content.to.storage.dir }}/{{ syncs3content.to.database.dir }}/{{ syncs3content.to.database.name }}.sql"
    state: absent

- name: "To S3: Uploading content"
  shell: "aws s3 sync . s3://{{ syncs3content.to.storage.bucket }} --profile {{ syncs3content.to.storage.profile }}"
  args:
    chdir: "{{ syncs3content.to.storage.dir }}"