---
- name: "To S3: Export the DB"
  become: yes
  mysql_db:
    name: "{{ syncs3content.to.database.name }}"
    state: dump
    target: "{{ syncs3content.to.storage.dir }}/{{ syncs3content.to.database.dir }}/{{ syncs3content.to.database.name }}.sql"
    login_host: "{{ syncs3content.to.database.host | default('localhost') }}"
    login_password: "{{ syncs3content.to.database.password | default('') }}"
    login_user: "{{ syncs3content.to.database.user | default('') }}"

- name: "To S3: Compress the DB"
  shell: "gzip -f {{ syncs3content.to.database.name }}.sql"
  args:
    chdir: "{{ syncs3content.to.storage.dir }}/{{ syncs3content.to.database.dir }}"

- name: "To S3: Uploading content"
  shell: "aws s3 sync . s3://{{ syncs3content.to.storage.bucket }} --profile {{ syncs3content.to.storage.profile }}"
  args:
    chdir: "{{ syncs3content.to.storage.dir }}"
  async: 3600
  poll: 0

- name: "To S3: Send notification to Slack"
  slack:
    token: "{{ syncs3content.slack.token }}"
    msg: "{{ syncs3content.slack.message }}"
    attachments:
      - title: "Sync content to S3"
        text: "{{ syncs3content.to.description }}"
        color: good
        fields:
          - title: "DataBase"
            value: "{{ syncs3content.to.database.name }}"
            short: "true"
          - title: "S3 Bucket"
            value: "{{ syncs3content.to.storage.bucket }}"
            short: "true"
          - title: "Storage directory"
            value: "{{ syncs3content.to.storage.dir }}"
            short: "true"
          - title: "Action"
            value: "{{ syncs3content.action }}"
            short: "true"
    username: "{{ syncs3content.slack.username }}"
    channel: "{{ syncs3content.slack.channel }}"
    icon_emoji: "{{ syncs3content.slack.icon_emoji }}"
  when: syncs3content.slack.token is defined
